# Generated by Django 4.2.4 on 2023-08-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('description', models.TextField(verbose_name='Описание')),
                ('photo', models.ImageField(upload_to='leaders/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('document', models.FileField(upload_to='lots/', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Лот',
                'verbose_name_plural': 'Лоты',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('video', models.URLField(verbose_name='Видео')),
                ('date', models.DateField(verbose_name='Дата')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date', models.DateField(verbose_name='Дата')),
                ('photo', models.ImageField(upload_to='services/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calls_today', models.PositiveIntegerField(verbose_name='Звонки сегодня')),
                ('calls_total', models.PositiveIntegerField(verbose_name='Звонки за все время')),
                ('subscribers_count', models.PositiveIntegerField(verbose_name='Количество абонентов')),
                ('water_pipe_kilometers', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Километры водопроводных сетей')),
                ('sewer_pipe_kilometers', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Километры канализационных сетей')),
                ('water_intakes', models.PositiveIntegerField(verbose_name='Водозаборные сооружения')),
            ],
            options={
                'verbose_name': 'Статистика',
                'verbose_name_plural': 'Статистика',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('content', models.TextField(verbose_name='Контент')),
                ('date', models.DateField(verbose_name='Дата')),
                ('photo', models.ImageField(upload_to='subscribers/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Для абонентов',
                'verbose_name_plural': 'Для абонентов',
            },
        ),
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес доставки')),
                ('contest_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма конкурса')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('bid_results', models.TextField(verbose_name='Результаты вскрытия и оценки заявок')),
                ('lots', models.TextField(verbose_name='Лоты')),
            ],
            options={
                'verbose_name': 'Тендер',
                'verbose_name_plural': 'Тендеры',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=100, verbose_name='Профессия')),
                ('date', models.DateField(verbose_name='Дата')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
